define([
    "./RecaudacionMensajeDTO",
    "./CajaDTO",
    "./EncabezadoCajaDTO",
    "./MovimientoCajaDTO",
    "./BoletaEmitidaDTO",
    "./NcEmitidaDTO",
    "./BonoEmitidoDTO",
    "./BonoAnuladoDTO",
    "./CoberturaEmitidaDTO",
    "./DetalleEgresoDTO",
    "./DetalleEgresoAnuladoDTO",
    "./DetalleIngresoDTO",
    "./DetalleIngresoAnuladoDTO",
    "./CargoCobradoBoletaDTO",
    "./CargoCobradoBonosDTO",
    "./CargoCobradoAnticipoDTO",
    "./FormaPagoDTO",
    "./FormaPagoAnuladoDTO",
    "./ReembolsoDTO",
    "./PagoRelacionadaDTO",
    "./CierreCajaDTO"
], function(
    RecaudacionMensajeDTO,
    CajaDTO,
    EncabezadoCajaDTO,
    MovimientoCajaDTO,
    BoletaEmitidaDTO,
    NcEmitidaDTO,
    BonoEmitidoDTO,
    BonoAnuladoDTO,
    CoberturaEmitidaDTO,
    DetalleEgresoDTO,
    DetalleEgresoAnuladoDTO,
    DetalleIngresoDTO,
    DetalleIngresoAnuladoDTO,
    CargoCobradoBoletaDTO,
    CargoCobradoBonosDTO,
    CargoCobradoAnticipoDTO,
    FormaPagoDTO,
    FormaPagoAnuladoDTO,
    ReembolsoDTO,
    PagoRelacionadaDTO,
    CierreCajaDTO
) {
    return {
        RecaudacionMensajeDTO: RecaudacionMensajeDTO,
        CajaDTO: CajaDTO,
        EncabezadoCajaDTO: EncabezadoCajaDTO,
        MovimientoCajaDTO: MovimientoCajaDTO,
        BoletaEmitidaDTO: BoletaEmitidaDTO,
        NcEmitidaDTO: NcEmitidaDTO,
        BonoEmitidoDTO: BonoEmitidoDTO,
        BonoAnuladoDTO: BonoAnuladoDTO,
        CoberturaEmitidaDTO: CoberturaEmitidaDTO,
        DetalleEgresoDTO: DetalleEgresoDTO,
        DetalleEgresoAnuladoDTO: DetalleEgresoAnuladoDTO,
        DetalleIngresoDTO: DetalleIngresoDTO,
        DetalleIngresoAnuladoDTO: DetalleIngresoAnuladoDTO,
        CargoCobradoBoletaDTO: CargoCobradoBoletaDTO,
        CargoCobradoBonosDTO: CargoCobradoBonosDTO,
        CargoCobradoAnticipoDTO: CargoCobradoAnticipoDTO,
        FormaPagoDTO: FormaPagoDTO,
        FormaPagoAnuladoDTO: FormaPagoAnuladoDTO,
        ReembolsoDTO: ReembolsoDTO,
        PagoRelacionadaDTO: PagoRelacionadaDTO,
        CierreCajaDTO: CierreCajaDTO
    };
});
