/**
 * @NApiVersion 2.1
 * @NModuleScope Public
 * @NAuthor 2Win - Jorge Espinoza
 */
define([], function () {
    const errorMessages = {
        "INVALID_KEY_OR_REF": "Error: La referencia al registro o la clave interna es inválida. Verifique que el ID interno del registro al que intenta acceder o modificar existe y es correcto.",
        "USER_ERROR":
            "Error del Usuario: Se ha producido un error debido a una entrada o acción del usuario. Por favor, revise los datos ingresados y asegúrese de que todos los campos obligatorios estén completos y sean correctos.",
        "UNEXPECTED_ERROR":
            "Error Inesperado: Ha ocurrido un error inesperado en el sistema. Por favor, intente la operación de nuevo. Si el problema persiste, contacte al administrador del sistema.",
        "DUP_RCRD": "Registro Duplicado: Está intentando crear un registro que ya existe en el sistema. Verifique los datos para evitar duplicados.",
        "INSUFFICIENT_PERMISSION":
            "Permisos Insuficientes: No tiene los permisos necesarios para realizar esta acción o para acceder a este registro. Contacte al administrador para que revise sus roles y permisos.",
        "CANT_EDIT_STANDARD_OBJ": "No se pueden editar objetos estándar: Está intentando modificar un objeto estándar de NetSuite que no permite edición.",
        "TRANS_UNBALNCD": "Transacción Desbalanceada: La transacción no está balanceada. El total de débitos debe ser igual al total de créditos.",
        "INVALID_LOGIN_ATTEMPT": "Intento de Inicio de Sesión Inválido: Las credenciales proporcionadas son incorrectas. Por favor, verifique su usuario y contraseña.",
        "CUSTOM_FIELD_VALIDATION_ERROR": "Error de Validación de Campo Personalizado: El valor introducido en un campo personalizado no cumple con los criterios de validación definidos.",
        "INLINE_EDITING_ERROR":
            "Error de Edición en Línea: No se pudieron guardar los cambios realizados mediante la edición en línea. Intente refrescar la página o editar el registro en la vista completa.",
        "A_SCRIPT_IS_ATTEMPTING_TO_EDIT_THE_1_SUBLIST_THIS_SUBLIST_IS_CURRENTLY_IN_READONLY_MODE_ AND_CANNOT_BE_EDITED_CALL_YOUR_NETSUITE_ADMINISTRATOR_TO_DISABLE_THIS_SCRIPT_IF_YOU_NEED_TO_SUBMIT_THIS_RECORD":
            "Un script está intentando editar la sublista {1}. Esta sublista está actualmente en modo de solo lectura y no puede ser editada. Contacte a su administrador de NetSuite para deshabilitar este script si necesita guardar este registro.",
        "AT_LEAST_ONE_EXPRESSION_IS_NEEDED": "Se necesita al menos una expresión.",
        "BUTTONS_MUST_INCLUDE_BOTH_A_LABEL_AND_VALUE": "Los botones deben incluir tanto una etiqueta como un valor.",
        "CAN_REFERENCE_ONLY_PERSISTED_DATASET": "Solo se puede hacer referencia a un conjunto de datos persistido.",
        "CAN_SELECT_ONLY_ONE_DEFAULT_CHOICE": "Solo se puede seleccionar una opción por defecto.",
        "CANNOT_CREATE_RECORD_DRAFT_OF_EXISTING_RECORD": "No se puede crear un borrador de un registro ya existente.",
        "CANNOT_CREATE_RECORD_INSTANCE": "No se puede crear una instancia del registro.",
        "CANNOT_DETERMINE_TYPE_FOR_ALIAS": "No se puede determinar el tipo para el alias.",
        "CANNOT_DETERMINE_VALUE_FOR_ALIAS": "No se puede determinar el valor para el alias.",
        "CANNOT_RESUBMIT_SUBMITTED_ASYNC_PIVOT_TASK": "No se puede volver a enviar una tarea de pivote asíncrona ya enviada.",
        "CANNOT_RESUBMIT_SUBMITTED_ASYNC_QUERY_TASK": "No se puede volver a enviar una tarea de consulta asíncrona ya enviada.",
        "CANNOT_RESUBMIT_SUBMITTED_ASYNC_SEARCH_TASK": "No se puede volver a enviar una tarea de búsqueda asíncrona ya enviada.",
        "CANNOT_RESUBMIT_SUBMITTED_ASYNC_SUITEQL_TASK": "No se puede volver a enviar una tarea de SuiteQL asíncrona ya enviada.",
        "COLOR_VALUE_MUST_BE_6_HEXADECIMAL_DIGITS_OF_THE_FORM_RRGGBB__EXAMPLE_FF0000_FOR_RED": "El valor del color debe ser de 6 dígitos hexadecimales en formato RRGGBB (ejemplo: FF0000 para rojo).",
        "CREDIT_CARD_NUMBER_IS_NOT_VALID__PLEASE_CHECK_THAT_ALL_DIGITS_WERE_ENTERED_CORRECTLY":
            "El número de la tarjeta de crédito no es válido. Por favor, verifique que todos los dígitos se hayan introducido correctamente.",
        "CREDIT_CARD_NUMBER_MUST_CONTAIN_BETWEEN_13_AND_20_DIGITS": "El número de la tarjeta de crédito debe contener entre 13 y 20 dígitos.",
        "CREDIT_CARD_NUMBER_MUST_CONTAIN_ONLY_DIGITS": "El número de la tarjeta de crédito debe contener solo dígitos.",
        "DATASET_NAME_IS_MISSING": "Falta el nombre del conjunto de datos.",
        "DEFAULT_CHOICE_IS_MISSING": "Falta la opción por defecto.",
        "EACH_VIEW_MUST_HAVE_AN_ID": "Cada vista debe tener un ID.",
        "EACH_VIEW_MUST_HAVE_A_NAME": "Cada vista debe tener un nombre.",
        "EMPTY_KEY_NOT_ALLOWED": "No se permiten claves vacías.",
        "EMPTY_KEY_NOT_ALLOWED_FOR_1": "No se permiten claves vacías para {1}.",
        "EXPRESSION_CANNOT_BE_SPECIFIED_WHEN_USING_COUNT_DISTINCT_AGGREGATION": "No se puede especificar una expresión al usar la agregación COUNT (DISTINCT).",
        "EXPRESSION_MUST_BE_SPECIFIED_WHEN_USING_OTHER_THAN_COUNT_DISTINCT_AGGREGATION": "Se debe especificar una expresión al usar una agregación que no sea COUNT (DISTINCT).",
        "EXPRESSIONS_CANNOT_BE_SPECIFIED_WHEN_USING_OTHER_THAN_COUNT_DISTINCT_AGGREGATION": "No se pueden especificar expresiones al usar una agregación que no sea COUNT (DISTINCT).",
        "EXPRESSIONS_MUST_BE_SPECIFIED_WHEN_USING_COUNT_DISTINCT_AGGREGATION": "Se deben especificar expresiones al usar la agregación COUNT (DISTINCT).",
        "FAILED_AN_UNEXPECTED_ERROR_OCCURRED": "Falló. Ocurrió un error inesperado.",
        "FIELD_1_ALREADY_CONTAINS_A_SUBRECORD_YOU_CANNOT_CALL_CREATESUBRECORD": "El campo {1} ya contiene un subregistro. No puede llamar a createSubrecord.",
        "FIELD_1_CANNOT_BE_EMPTY": "El campo {1} no puede estar vacío.",
        "FIELD_1_IS_NOT_A_SUBRECORD_FIELD": "El campo {1} no es un campo de subregistro.",
        "FIELD_MUST_CONTAIN_A_VALUE": "El campo debe contener un valor.",
        "FORM_VALIDATION_FAILED_YOU_CANNOT_SUBMIT_THIS_RECORD": "Falló la validación del formulario. No puede guardar este registro.",
        "FORM_VALIDATION_FAILED_YOU_CANNOT_CREATE_THIS_SUBRECORD": "Falló la validación del formulario. No puede crear este subregistro.",
        "HISTORY_IS_ONLY_AVAILABLE_FOR_THE_LAST_30_DAYS": "El historial solo está disponible para los últimos 30 días.",
        "ID_CANNOT_HAVE_MORE_THAN_N_CHARACTERS": "El ID no puede tener más de N caracteres.",
        "IDENTIFIERS_CAN_CONTAIN_ONLY_DIGITS_ALPHABETIC_CHARACTERS_OR__WITH_NO_SPACES": "Los identificadores solo pueden contener dígitos, caracteres alfabéticos o _ (guion bajo), sin espacios.",
        "INVALID_AGGREGATE_TYPE": "Tipo de agregado inválido.",
        "INVALID_AGGREGATION": "Agregación inválida.",
        "INVALID_ALGORITHM": "Algoritmo inválido.",
        "INVALID_ALPHA_VALUE": "Valor alfa inválido.",
        "INVALID_ASPECT_TYPE": "Tipo de aspecto inválido.",
        "INVALID_CERTIFICATE_TYPE": "Tipo de certificado inválido.",
        "INVALID_CHART_TYPE": "Tipo de gráfico inválido.",
        "INVALID_COLOR_VALUE": "Valor de color inválido.",
        "INVALID_COLUMN_ALIAS": "Alias de columna inválido.",
        "INVALID_COLUMN_FOR_SORTING": "Columna inválida para ordenar.",
        "INVALID_CONFIGURATION_UNABLE_TO_CHANGE_REQUIRE_CONFIGURATION_FOR_1": "Configuración inválida. No se puede cambiar la configuración requerida para {1}.",
        "INVALID_CONFIGURATION_UNABLE_TO_CHANGE_REQUIRE_CONFIGURATION_WITHOUT_A_CONTEXT": "Configuración inválida. No se puede cambiar la configuración requerida sin un contexto.",
        "INVALID_CONFLICT_RESOLUTION_1": "Resolución de conflicto inválida: {1}.",
        "INVALID_CURRENCY": "Moneda inválida.",
        "INVALID_CUSTOM_VIEW_VALUE": "Valor de vista personalizada inválido.",
        "INVALID_DATASET_ID": "ID de conjunto de datos inválido.",
        "INVALID_DATE_ID": "ID de fecha inválido.",
        "INVALID_DATE_VALUE_MUST_BE_ON_OR_AFTER_1CUTOFF_DATE": "La fecha debe ser igual o posterior a la fecha de corte {1}.",
        "INVALID_DATE_VALUE_MUST_BE_1": "El valor de la fecha debe ser {1}.",
        "INVALID_DATE_OBJECT": "Objeto de fecha inválido.",
        "INVALID_DIRECTION_FOR_SORTING": "Dirección de ordenamiento inválida.",
        "INVALID_EMAILS_FOUND": "Se encontraron correos electrónicos inválidos.",
        "INVALID_EXPRESSION": "Expresión inválida.",
        "INVALID_FIELD_CONTEXT": "Contexto de campo inválido.",
        "INVALID_FIELD_ID": "ID de campo inválido.",
        "INVALID_FIELD_INDEX": "Índice de campo inválido.",
        "INVALID_FIELD_VALUE": "Valor de campo inválido.",
        "INVALID_FILTER_FIELD_FOR_CURRENT_VIEW": "Campo de filtro inválido para la vista actual.",
        "INVALID_FLD_VALUE": "Valor de campo inválido.",
        "INVALID_FONT_SIZE": "Tamaño de fuente inválido.",
        "INVALID_FONT_STYLE": "Estilo de fuente inválido.",
        "INVALID_FONT_WEIGHT": "Grosor de fuente inválido.",
        "INVALID_FORMULA_TYPE": "Tipo de fórmula inválido.",
        "INVALID_GETSELECTOPTION_FILTER_OPERATOR": "Operador de filtro getSelectOption inválido.",
        "INVALID_HTTP_METHOD": "Método HTTP inválido.",
        "INVALID_ID_PREFIX": "Prefijo de ID inválido.",
        "INVALID_IMAGE": "Imagen inválida.",
        "INVALID_KEY_TYPE": "Tipo de clave inválido.",
        "INVALID_LOCALE": "Configuración regional (locale) inválida.",
        "INVALID_NUMBER_MUST_BE_BETWEEN_1_AND_2": "El número debe estar entre {1} y {2}.",
        "INVALID_NUMBER_MUST_BE_GREATER_THAN_1": "El número debe ser mayor que {1}.",
        "INVALID_NUMBER_MUST_BE_LOWER_THAN_1": "El número debe ser menor que {1}.",
        "INVALID_NUMBER_OR_PERCENTAGE": "Número o porcentaje inválido.",
        "INVALID_OPERATION": "Operación inválida.",
        "INVALID_OPERATOR": "Operador inválido.",
        "INVALID_OR_UNSUPPORTED_RECORD_TYPE_1": "Tipo de registro inválido o no soportado: {1}.",
        "INVALID_OWNER_CATEGORY": "Categoría de propietario inválida.",
        "INVALID_PAGE_INDEX": "Índice de página inválido.",
        "INVALID_PAGE_RANGE": "Rango de página inválido.",
        "INVALID_PERIOD_ADJUSTMENT": "Ajuste de período inválido.",
        "INVALID_PERIOD_CODE": "Código de período inválido.",
        "INVALID_PERIOD_TYPE": "Tipo de período inválido.",
        "INVALID_POSITION": "Posición inválida.",
        "INVALID_RCRD_TYPE": "Tipo de registro inválido.",
        "INVALID_RETURN_TYPE_EXPECTED_1": "Tipo de retorno inválido. Se esperaba {1}.",
        "INVALID_SCRIPT_OPERATION_ON_READONLY_SUBLIST_FIELD": "Operación de script inválida en un campo de sublista de solo lectura.",
        "INVALID_SEARCH_OPERATOR": "Operador de búsqueda inválido.",
        "INVALID_SEARCH_TYPE": "Tipo de búsqueda inválido.",
        "INVALID_SIGNATURE": "Firma inválida.",
        "INVALID_SIGNATURE_TAG": "Etiqueta de firma inválida.",
        "INVALID_SORT": "Ordenamiento inválido.",
        "INVALID_SORT_LOCALE": "Configuración regional (locale) de ordenamiento inválida.",
        "INVALID_STACKING_TYPE": "Tipo de apilamiento inválido.",
        "INVALID_SUBLST_OPERATION": "Operación en sublista inválida.",
        "INVALID_SUBRECORD_MERGE": "Fusión de subregistro inválida.",
        "INVALID_SUITEAPP_APPLICATION_ID": "ID de aplicación SuiteApp inválido.",
        "INVALID_TASK_TYPE": "Tipo de tarea inválido.",
        "INVALID_TEPORAL_UNIT": "Unidad temporal inválida.",
        "INVALID_TEXT_ALIGN": "Alineación de texto inválida.",
        "INVALID_TEXT_DECORATION_LINE": "Línea de decoración de texto inválida.",
        "INVALID_TEXT_DECORATION_STYLE": "Estilo de decoración de texto inválido.",
        "INVALID_TOTAL_LINE": "Línea total inválida.",
        "INVALID_TYPE_1_USE_2": "Tipo inválido {1}. Use {2}.",
        "INVALID_UI_OBJECT_TYPE": "Tipo de objeto de interfaz de usuario (UI) inválido.",
        "INVALID_UNIT": "Unidad inválida.",
        "INVALID_URL_SPACES_ARE_NOT_ALLOWED_IN_THE_URL": "URL inválida. No se permiten espacios en la URL.",
        "INVALID_URL_URL_MUST_START_WITH_HTTP_HTTPS_FTP_OR_FILE": "URL inválida. La URL debe comenzar con http, https, ftp o file.",
        "INVALID_WORKBOOK_ID": "ID de libro de trabajo (workbook) inválido.",
        "METHOD_IS_ONLY_ALLOWED_FOR_MATRIX_FIELD": "Este método solo está permitido para campos de tipo matriz.",
        "MISSING_MANDATORY_FIELDS": "Faltan campos obligatorios.",
        "MISSING_REQD_ARGUMENT": "Falta un argumento requerido.",
        "MUTUALLY_EXCLUSIVE_ARGUMENTS": "Argumentos mutuamente excluyentes.",
        "NAME_CANNOT_BE_EMPTY": "El nombre no puede estar vacío.",
        "NAME_CANNOT_HAVE_MORE_THAN_N_CHARACTERS": "El nombre no puede tener más de N caracteres.",
        "NEITHER_ARGUMENT_DEFINED": "Ninguno de los argumentos está definido.",
        "NO_ASPECTS_DEFINED": "No se han definido aspectos.",
        "NO_CHILDREN_DEFINED": "No se han definido hijos.",
        "NO_COLUMN_DEFINED": "No se ha definido ninguna columna.",
        "NO_DATASET_DEFINED": "No se ha definido ningún conjunto de datos.",
        "NO_DIMENSION_ITEM_DEFINED": "No se ha definido ningún elemento de dimensión.",
        "NO_ELEMENTS_DEFINED": "No se han definido elementos.",
        "NO_MEASURES_DEFINED": "No se han definido medidas.",
        "NO_RULE_DEFINED": "No se ha definido ninguna regla.",
        "NO_SELECTORS_DEFINED": "No se han definido selectores.",
        "NO_SORT_BY_DEFINED": "No se ha definido un criterio de ordenamiento.",
        "NON_KATAKANA_DATA_FOUND": "Se encontraron datos que no son Katakana.",
        "NOT_SUPPORTED_ON_CURRENT_SUBRECORD": "No soportado en el subregistro actual.",
        "NOTICE_THE_CREDIT_CARD_APPEARS_TO_BE_INCORRECT": "Aviso: El número de la tarjeta de crédito parece ser incorrecto.",
        "OPERATOR_ARITY_MISMATCH": "Discrepancia en la aridad del operador.",
        "OPERATION_IS_NOT_ALLOWED": "La operación no está permitida.",
        "PASSWORD_CANNOT_HAVE_MORE_THAN_N_CHARACTERS": "La contraseña no puede tener más de N caracteres.",
        "PHONE_NUMBER_SHOULD_HAVE_SEVEN_DIGITS_OR_MORE": "El número de teléfono debe tener siete dígitos o más.",
        "PIVOT_DOES_NOT_EXIST": "El pivote no existe.",
        "PLEASE_ENTER_A_VALID_FROM_START_DATE_IN_MMYYYY_FORMAT": "Por favor, introduzca una fecha de inicio válida en formato MM/AAAA.",
        "PLEASE_ENTER_AN_EXPIRATION_DATE_IN_MMYYYY_FORMAT": "Por favor, introduzca una fecha de vencimiento en formato MM/AAAA.",
        "PLEASE_INCLUDE_THE_AREA_CODE_FOR_PHONE_NUMBER": "Por favor, incluya el código de área para el número de teléfono.",
        "PROPERTY_VALUE_CONFLICT": "Conflicto de valor de propiedad.",
        "READ_ONLY_PROPERTY": "Propiedad de solo lectura.",
        "RELATIONSHIP_ALREADY_USED": "La relación ya está en uso.",
        "SCRIPT_EXECUTION_USAGE_LIMIT_EXCEEDED": "Se ha excedido el límite de uso de ejecución de script.",
        "SELECT_OPTION_ALREADY_PRESENT": "La opción de selección ya existe.",
        "SELECT_OPTION_NOT_FOUND": "No se encontró la opción de selección.",
        "SERVER_SIDE_VALIDATION_FAILED": "Falló la validación del lado del servidor.",
        "SIGNATURE_VERIFICATION_FAILED": "Falló la verificación de la firma.",
        "SSS_ARGUMENT_DISCREPANCY": "Discrepancia en los argumentos (SSS).",
        "SSS_DUPLICATE_ALIAS": "Alias duplicado (SSS).",
        "SSS_INVALID_ACTION_ID": "ID de acción inválido (SSS).",
        "SSS_INVALID_API_USAGE": "Uso de API inválido (SSS).",
        "SSS_INVALID_COUNTRY_ID": "ID de país inválido (SSS).",
        "SSS_INVALID_CURRENCY_ID": "ID de moneda inválido (SSS).",
        "SSS_INVALID_FORMAT_TYPE": "Tipo de formato inválido (SSS).",
        "SSS_INVALID_GETSELECTOPTION_FILTER_OPERATOR": "Operador de filtro getSelectOption inválido (SSS).",
        "SSS_INVALID_MACRO_ID": "ID de macro inválido (SSS).",
        "SSS_INVALID_READ_SIZE": "Tamaño de lectura inválido (SSS).",
        "SSS_INVALID_SEARCH_RESULT_INDEX": "Índice de resultado de búsqueda inválido (SSS).",
        "SSS_INVALID_SEGMENT_SEPARATOR": "Separador de segmento inválido (SSS).",
        "SSS_INVALID_SRCH_OPERATOR": "Operador de búsqueda inválido (SSS).",
        "SSS_INVALID_SUBLIST": "Sublista inválida (SSS).",
        "SSS_INVALID_SUBLIST_OPERATION": "Operación en sublista inválida (SSS).",
        "SSS_INVALID_TYPE_ARG": "Argumento de tipo inválido (SSS).",
        "SSS_INVALID_UI_OBJECT_TYPE": "Tipo de objeto de UI inválido (SSS).",
        "SSS_INVALID_URL": "URL inválida (SSS).",
        "SSS_METHOD_IS_ONLY_ALLOWED_FOR_MATRIX_FIELD": "Este método solo está permitido para campos de matriz (SSS).",
        "SSS_METHOD_IS_ONLY_ALLOWED_FOR_MULTISELECT_FIELD": "Este método solo está permitido para campos de selección múltiple (SSS).",
        "SSS_METHOD_IS_ONLY_ALLOWED_FOR_SELECT_FIELD": "Este método solo está permitido para campos de selección (SSS).",
        "SSS_MISSING_ALIAS": "Falta el alias (SSS).",
        "SSS_MISSING_REQD_ARGUMENT": "Falta un argumento requerido (SSS).",
        "SSS_NOT_YET_SUPPORTED": "Aún no soportado (SSS).",
        "SSS_RECORD_DOES_NOT_SATISFY_CONDITION": "El registro no cumple la condición (SSS).",
        "SSS_RECORD_TYPE_MISMATCH": "El tipo de registro no coincide (SSS).",
        "SSS_SEARCH_FOR_EACH_LIMIT_EXCEEDED": "Se excedió el límite de la búsqueda forEach (SSS).",
        "SSS_SEARCH_RESULT_LIMIT_EXCEEDED": "Se excedió el límite de resultados de búsqueda (SSS).",
        "SSS_SUBLIST_DOESNT_SUPPORT_MOVING_LINES": "La sublista no soporta mover líneas (SSS).",
        "SSS_TAG_CANNOT_BE_EMPTY": "La etiqueta no puede estar vacía (SSS).",
        "SSS_TAX_REGISTRATION_REQUIRED": "Se requiere registro de impuestos (SSS).",
        "SSS_UNSUPPORTED_METHOD": "Método no soportado (SSS).",
        "TABLE_DOES_NOT_EXIST": "La tabla no existe.",
        "THAT_RECORD_IS_NOT_EDITABLE": "Ese registro no es editable.",
        "THE_FIELD_1_CONTAINED_MORE_THAN_THE_MAXIMUM_NUMBER__2__OF_CHARACTERS_ALLOWED": "El campo {1} contiene más del número máximo de caracteres permitidos ({2}).",
        "THE_OPTIONS_ARE_MUTUALLY_EXCLUSIVE_1_2_ARG2_": "Las opciones son mutuamente excluyentes: {1}, {2}.",
        "TOO_MANY_RESULTS": "Demasiados resultados.",
        "TRANSLATION_HANDLE_IS_IN_AN_ILLEGAL_STATE": "El manejador de traducción está en un estado ilegal.",
        "UNHANDLED_ERRORS_ON_RESTORE": "Errores no manejados en la restauración.",
        "UNKNOWN_CONTEXT_TYPE": "Tipo de contexto desconocido.",
        "UNKNOWN_PARAM": "Parámetro desconocido.",
        "UNSUPPORTED_COLOR": "Color no soportado.",
        "VALUE_1_OUTSIDE_OF_VALID_MINMAX_RANGE_FOR_FIELD2": "El valor {1} está fuera del rango válido (mín/máx) para el campo {2}.",
        "WORKBOOK_NAME_IS_MISSING": "Falta el nombre del libro de trabajo (workbook).",
        "WRONG_PARAMETER_TYPE": "Tipo de parámetro incorrecto.",
        "WS_INVALID_REFERENCE_KEY_1": "Clave de referencia inválida en servicio web (WS): {1}.",
        "WS_NO_PERMISSIONS_TO_SET_VALUE": "Sin permisos para establecer el valor (WS).",
        "YOU_HAVE_ATTEMPTED_AN_UNSUPPORTED_ACTION": "Ha intentado una acción no soportada.",
        "SSS_SEARCH_ERROR_OCCURRED": "Ocurrió un error en la búsqueda (SSS). Por favor, revise los filtros y parámetros utilizados.",
        "SSS_INVALID_SEARCH_TYPE": "Tipo de búsqueda inválido (SSS). Asegúrese de que el tipo de búsqueda sea correcto y esté soportado por la API.",
        "SSS_INVALID_SEARCH_OPERATOR": "Operador de búsqueda inválido (SSS). Verifique que el operador utilizado sea válido para el tipo de búsqueda.",
        "SSS_INVALID_SEARCH_FILTER": "Filtro de búsqueda inválido (SSS). Verifique que los filtros utilizados sean correctos y estén soportados por la API."
    };

    /**
     * Devuelve el mensaje de error en español para un código de error de NetSuite.
     * Si el código de error no se encuentra, devuelve un mensaje genérico.
     * @param {string} errorCode - El código de error de NetSuite (e.g., e.name).
     * @returns {string} - El mensaje de error traducido.
     */
    function errorHandler(err) {
        const auxError = JSON.parse(JSON.stringify(err));
        if (errorMessages[auxError.name]) {
            auxError.message = errorMessages[auxError.name];
        }
        return {
            name: auxError.name || "CUSTOM_VALIDATION_ERROR",
            message: auxError.message,
            notifyOff: true
        };
    }

    return {
        errorHandler: errorHandler
    };
});
